add[practica-12-12 and 17-12] lit element done and working
alfonsorios96/academia-ironbit-2019 pull request #64
Opened 2019-12-17 23:29 UTC by Pulgaron

2019-12-18 16:32 UTC, alfonsorios96 requested changes

2019-12-18 16:32 UTC, alfonsorios96 commented on Pulgaron/practica-2019-12-12/classesScheam.js
> +
Empty methods

2019-12-22 23:54 UTC, Pulgaron commented on Pulgaron/practica-2019-12-12/classesScheam.js
> +
fixed

2019-12-23 14:24 UTC, alfonsorios96 requested changes
Remove .idea/ and package-lock.json

2019-12-30 16:19 UTC, closed without merging